<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Register</name>
   <tag></tag>
   <elementGuidId>47428533-7b1e-4ed4-93ed-28d0d1d6c888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Account'])[1]/following::h2[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.mb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a1ac67b5-50cc-4c95-a487-2d654cf433e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-3</value>
      <webElementGuid>6853f922-6822-489c-920e-ef3f469af2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>e4db0831-65ad-45a3-a0c6-1bbda496b32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-register[1]/html[1]/body[1]/section[1]/div[@class=&quot;px-4 py-5 px-md-5 text-center text-lg-start&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row gx-lg-5 align-items-center&quot;]/div[@class=&quot;col-lg-6 mb-5 mb-lg-0&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-3 px-md-5&quot;]/div[@class=&quot;container&quot;]/h2[@class=&quot;mb-3&quot;]</value>
      <webElementGuid>05c9cf62-7898-4a29-9200-fefa62e52825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Account'])[1]/following::h2[1]</value>
      <webElementGuid>34f4c5be-b8fa-41f4-a00e-97bb4514641f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::h2[1]</value>
      <webElementGuid>829da760-9618-4430-97cb-e7e53a22388e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::h2[1]</value>
      <webElementGuid>a944d714-289c-489c-a972-b1667ebb4878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>7e9f836f-f6d4-4b9d-b332-5effe86227c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>8d416e74-0cda-4a1b-930c-ff807234a7be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
